version: '3'
services:
  chrome:
    image: selenium/standalone-chrome
    shm_size: '4gb'
    ports:
      - 4444:4444 # Selenium service
      - 5900:5900 # VNC server
      - 7900:7900 # VNC browser client
    environment:
      - SE_VNC_PASSWORD=test

