# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
#      matrix:
#        browser: ['chrome', 'firefox', 'edge']
    container:
      image: node:19

    services:
      selenium:
        image: selenium/standalone-${{ github.event.inputs.browser }}
        options: --shm-size=2gb

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.9'
  
      - name: Build
        run: go build -v  -o web ./...
      - run: ./../web &      
      - run: sleep 10
      - run: 
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven  
      - name: Build with Maven
        run: mvn -f selenium/pom.xml compile exec:java -Dexec.mainClass="com.example.Test"
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: selenium/screenshots/

