# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
#      matrix:
#        browser: ['chrome', 'firefox', 'edge']
    container:
      image: node:19

    services:
      selenium:
        image: selenium/standalone-firefox
        options: --shm-size=4gb

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v4
      - run: git config --global --add safe.directory ./...

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.9'
  
      - name: Build
        run: go build -v  -o web -buildvcs=false ./...
      - run: ./../web &      
      - run: sleep 1

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'      
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2
      - name: Build with Maven
        run: |
          mkdir screenshots;
          mvn -f selenium/pom.xml compile exec:java -Dexec.mainClass="com.example.Test"l
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: screenshots/

